CREATE TABLE IF NOT EXISTS `TB_USER_PERMISSION` (
  `ID_USER` BIGINT(20) NOT NULL,
  `ID_PERMISSION` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID_USER`,`ID_PERMISSION`),
  KEY `FK_USER_PERMISSION_PERMISSION` (`ID_PERMISSION`),
  CONSTRAINT `FK_USER_PERMISSION` FOREIGN KEY (`ID_USER`) REFERENCES `TB_USERS` (`ID`),
  CONSTRAINT `FK_USER_PERMISSION_PERMISSION` FOREIGN KEY (`ID_PERMISSION`) REFERENCES `TB_PERMISSION` (`ID`)
) ENGINE=InnoDB;