INSERT INTO `TB_UNIDADE` (ID, NOME, ENDERECO, STATUS) VALUES 
	(1,'CASCADURA','RUA C 1','ATIVA'),
	(2,'MADUREIRA','RUA M 1','ATIVA'),
	(3,'OSWALDO CRUZ','RUA O 1','ATIVA'),
	(5,'MARECHAL HERMES','RUA M 2','ATIVA'),
	(6,'OLARIA','RUA O 2','ATIVA');