CREATE TABLE IF NOT EXISTS `TB_TURMA` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`UNIDADE_ID`BIGINT NOT NULL,
	`NOME` VARCHAR(80) NOT NULL,	
	`STATUS` VARCHAR(20) NOT NULL COMMENT 'DESATIVADA(0, "Desativada"), ATIVA(1, "Ativa"), INVALIDA(100, "Status inválido")',	
	PRIMARY KEY (`ID`),
	INDEX `FK_TB_TURMA_TB_UNIDADE_IDX` (`UNIDADE_ID` ASC),
  	UNIQUE INDEX `NOME_UNIDADE_ID_UK`
  			(`NOME` ASC, `UNIDADE_ID` ASC) COMMENT 'O nome da turma pode se repetir desde que seja para unidades diferentes\nex nome 1001 unidade_id 1\nnome 1001 unidade_id 2',
  	CONSTRAINT `FK_TB_TURMA_TB_UNIDADE`
    FOREIGN KEY (`UNIDADE_ID`)
    REFERENCES `DB_CURSO`.`TB_UNIDADE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);