USE db_curso;

CREATE TABLE IF NOT EXISTS `tb_users` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(255) DEFAULT NULL,
  `FULL_NAME` VARCHAR(255) DEFAULT NULL,
  `PASSWORD` VARCHAR(255) DEFAULT NULL,
  `ACCOUNT_NON_EXPIRED` BIT(1) DEFAULT NULL,
  `ACCOUNT_NON_LOCKED` BIT(1) DEFAULT NULL,
  `CREDENTIALS_NON_EXPIRED` BIT(1) DEFAULT NULL,
  `ENABLED` BIT(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB;