USE db_curso;

CREATE TABLE IF NOT EXISTS `tb_parcela` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CONTRATO_ID` BIGINT(20) NOT NULL,
  `DT_VENC` DATE NOT NULL,
  `VLR_PG` DECIMAL(7,2) DEFAULT NULL COMMENT 'VALOR PAGO NESTA DATA',
  `DT_PG` DATE DEFAULT NULL,
  `VLR_PARC_CURSO` DECIMAL(7,2) NOT NULL COMMENT 'VALOR COM DESCONTO E PARCELADO',
  `VLR_PARC_MATE` DECIMAL(7,2) NOT NULL COMMENT 'VALOR PARCELADO',
  `VLR_TOT_PARC` DECIMAL(7,2) NOT NULL COMMENT 'PARCELA_CURSO+PARCELA_MATERIAL+TAXA_MATRICULA',
  `SIT_PARC` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_TB_PARCELA_TB_CONTRATO_IDX` (`CONTRATO_ID`),
  CONSTRAINT `FK_TB_PARCELA_TB_CONTRATO` FOREIGN KEY (`CONTRATO_ID`) REFERENCES `tb_contrato` (`ID`)
  ON DELETE NO ACTION 
  ON UPDATE NO ACTION
);

SET character_set_client = utf8;
SET character_set_connection = utf8;
SET character_set_results = utf8;
SET collation_connection = utf8_general_ci;